//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Ellucian.Generated.BpApi.Ban.InvoiceCreditMemo100PutRequest
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class InvoiceCreditMemo100PutRequest
    {
        /// <summary>
        /// Lineage reference object : FABINVH_VEND_INV_CODE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.vendInvCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaVendInvCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_USER_ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.userId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaUserId { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_ACTIVITY_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.activityDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? CriteriaActivityDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_INVOICE_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.invoiceDate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset CriteriaInvoiceDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("criteria.matchTempReq", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaMatchTempReq { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_INVOICE_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fabinvhInvoiceDate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset FabinvhInvoiceDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_VEND_INV_CODE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fabinvhVendInvCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FabinvhVendInvCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_1099_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.1099Ind", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Criteria1099Ind { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_SINGLE_ACCTG_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fabinvhSingleAcctgInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FabinvhSingleAcctgInd { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("criteria.faainvhVendCheckCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaFaainvhVendCheckCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : keyBlockVendor
        /// </summary>
        [Newtonsoft.Json.JsonProperty("vendor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Vendor { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_ACHT_CODE, Lookup lineage reference object : gtvacht
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.achtCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaAchtCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("criteria.addrLine4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaAddrLine4 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_PMT_DUE_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("pmtDueDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? PmtDueDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_SINGLE_ACCTG_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.singleAcctgInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaSingleAcctgInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_TRANS_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.transDate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset CriteriaTransDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("criteria.houseNumber", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaHouseNumber { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_ACH_OVERRIDE_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.achOverrideInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaAchOverrideInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_CR_MEMO_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.crMemoInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaCrMemoInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_CR_MEMO_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fabinvhCrMemoInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FabinvhCrMemoInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : faainvhDocCode
        /// </summary>
        [Newtonsoft.Json.JsonProperty("faainvhDocCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FaainvhDocCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_MULTIPLE_INV_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.multipleInvInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaMultipleInvInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : invoiceChoice
        /// </summary>
        [Newtonsoft.Json.JsonProperty("invoiceChoice", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string InvoiceChoice { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_PMT_DUE_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.pmtDueDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? CriteriaPmtDueDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : FABINVH_BANK_CODE, Lookup lineage reference object : gxvbank
        /// </summary>
        [Newtonsoft.Json.JsonProperty("criteria.bankCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaBankCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("criteria.headerText", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CriteriaHeaderText { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603