//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Ellucian.Generated.BpApi.Ban.LocationHierarchyQueryV100GetResponse
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class LocationHierarchyQueryV100GetResponse
    {
        /// <summary>
        /// Lineage reference object : level5
        /// </summary>
        [Newtonsoft.Json.JsonProperty("level5", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Level5 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : level4
        /// </summary>
        [Newtonsoft.Json.JsonProperty("level4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Level4 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : hpPredLocnCode
        /// </summary>
        [Newtonsoft.Json.JsonProperty("hpPredLocnCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? HpPredLocnCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : titl1
        /// </summary>
        [Newtonsoft.Json.JsonProperty("titl1", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Titl1 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : titl2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("titl2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Titl2 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : titl3
        /// </summary>
        [Newtonsoft.Json.JsonProperty("titl3", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Titl3 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : titl4
        /// </summary>
        [Newtonsoft.Json.JsonProperty("titl4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Titl4 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : predTitle
        /// </summary>
        [Newtonsoft.Json.JsonProperty("predTitle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PredTitle { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : head1
        /// </summary>
        [Newtonsoft.Json.JsonProperty("head1", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Head1 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : head2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("head2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Head2 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : head3
        /// </summary>
        [Newtonsoft.Json.JsonProperty("head3", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Head3 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : head4
        /// </summary>
        [Newtonsoft.Json.JsonProperty("head4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Head4 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : level1
        /// </summary>
        [Newtonsoft.Json.JsonProperty("level1", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Level1 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : titl5
        /// </summary>
        [Newtonsoft.Json.JsonProperty("titl5", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Titl5 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : head5
        /// </summary>
        [Newtonsoft.Json.JsonProperty("head5", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Head5 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : level3
        /// </summary>
        [Newtonsoft.Json.JsonProperty("level3", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Level3 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : level2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("level2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Level2 { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603