//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Ellucian.Generated.BpApi.Ban.RegistrationSections100GetResponse
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RegistrationSections100GetResponse
    {
        [Newtonsoft.Json.JsonProperty("sfvsttm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<object>? Sfvsttm { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sfvstum", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sfvstum>? Sfvstum { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sfvsecm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sfvsecm>? Sfvsecm { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sfvstum
    {
        [Newtonsoft.Json.JsonProperty("squeryLinkIdent", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SqueryLinkIdent { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squeryCrseNumb", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SqueryCrseNumb { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squerySstsCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SquerySstsCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squeryCampCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SqueryCampCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squeryPtrmCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SqueryPtrmCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSTUM_ERROR_FLAG
        /// </summary>
        [Newtonsoft.Json.JsonProperty("errorFlag", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ErrorFlag { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squeryXlstGroup", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SqueryXlstGroup { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode1", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode1 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode2 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode3", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode3 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squerySeqNumb", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SquerySeqNumb { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode4 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squeryWaitCount", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? SqueryWaitCount { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode5", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode5 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode6", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode6 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode7", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode7 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSTUM_RSTS_CODE, Lookup lineage reference object : stvrsts
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rstsCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RstsCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stumBlockInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StumBlockInd { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squerySeatsAvail", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? SquerySeatsAvail { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squerySubjCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SquerySubjCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squeryCrn", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SqueryCrn { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSTUM_BEGIN_TIME
        /// </summary>
        [Newtonsoft.Json.JsonProperty("beginTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BeginTime { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSTUM_END_TIME
        /// </summary>
        [Newtonsoft.Json.JsonProperty("endTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EndTime { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("squerySchdCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SquerySchdCode { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sfvsecm
    {
        [Newtonsoft.Json.JsonProperty("timeconflict", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Timeconflict { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("queryCrn", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QueryCrn { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvsubj
        /// </summary>
        [Newtonsoft.Json.JsonProperty("querySubjCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QuerySubjCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSECM_SEATS_AVAIL
        /// </summary>
        [Newtonsoft.Json.JsonProperty("seatsAvail", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? SeatsAvail { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("queryXlstGroup", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QueryXlstGroup { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode1", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode1 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode2 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode3", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode3 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("blockInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BlockInd { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvschd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("querySchdCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QuerySchdCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode4", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode4 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("queryCrseNumb", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QueryCrseNumb { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode5", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode5 { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode6", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode6 { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvptrm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("queryPtrmCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QueryPtrmCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("daysCode7", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DaysCode7 { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvcamp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("queryCampCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QueryCampCode { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvssts
        /// </summary>
        [Newtonsoft.Json.JsonProperty("querySstsCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QuerySstsCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSECM_BEGIN_TIME
        /// </summary>
        [Newtonsoft.Json.JsonProperty("beginTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BeginTime { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSECM_END_TIME
        /// </summary>
        [Newtonsoft.Json.JsonProperty("endTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EndTime { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFVSECM_WAIT_COUNT
        /// </summary>
        [Newtonsoft.Json.JsonProperty("waitCount", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? WaitCount { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("queryLinkIdent", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QueryLinkIdent { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("querySeqNumb", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? QuerySeqNumb { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603