//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Ellucian.Generated.BpApi.Ban.StudentCourseRegistrationsV100GetResponse
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class StudentCourseRegistrationsV100GetResponse
    {
        [Newtonsoft.Json.JsonProperty("sftdwer", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sftdwer>? Sftdwer { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sfrcolr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sfrcolr>? Sfrcolr { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sftregs", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sftregs>? Sftregs { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sfbetrm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sfbetrm>? Sfbetrm { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sfrensp", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sfrensp>? Sfrensp { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sgbstdn", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sgbstdn>? Sgbstdn { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sorlcur", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sorlcur>? Sorlcur { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sorlfos", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sorlfos>? Sorlfos { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("s$_curricula_traditional", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<S_curricula_traditional>? S_curricula_traditional { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("s$_studypath", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<object>? S_studypath { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sgrstsp", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sgrstsp>? Sgrstsp { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sfrthst", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Sfrthst>? Sfrthst { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sftdwer
    {
        /// <summary>
        /// Lineage reference object : SFTDWER_ERROR_MESSAGE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("errorMessage", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ErrorMessage { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sfrcolr
    {
        [Newtonsoft.Json.JsonProperty("assessFees", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AssessFees { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("hold", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Hold { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sftregs
    {
        [Newtonsoft.Json.JsonProperty("attemptHr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? AttemptHr { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_GMOD_CODE, Lookup lineage reference object : stvgmod,scrgmod,scrgmod
        /// </summary>
        [Newtonsoft.Json.JsonProperty("gmodCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string GmodCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_STSP_KEY_SEQUENCE, Lookup lineage reference object : sgvstsp,stvcast,stvastd,stvests,sfrensp,sgrstsp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("stspKeySequence", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? StspKeySequence { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_BILL_HR
        /// </summary>
        [Newtonsoft.Json.JsonProperty("billHr", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double BillHr { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_CREDIT_HR
        /// </summary>
        [Newtonsoft.Json.JsonProperty("creditHr", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double CreditHr { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("ssbsectSeqNumb", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SsbsectSeqNumb { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_APPR_RECEIVED_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("apprReceivedInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ApprReceivedInd { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("rwoverride", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Rwoverride { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("frDiscountCrnDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FrDiscountCrnDisplay { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvsubj
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ssbsectSubjCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SsbsectSubjCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("tmstHr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? TmstHr { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("ssbsectCrseNumb", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string SsbsectCrseNumb { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_PTRM_CODE, Lookup lineage reference object : stvptrm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ptrmCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PtrmCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("errorFlagDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ErrorFlagDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_RSTS_CODE, Lookup lineage reference object : stvrsts
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rstsCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string RstsCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_CAMP_CODE, Lookup lineage reference object : stvcamp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("campCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CampCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("vrStatusTypeDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? VrStatusTypeDisplay { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("ssbsectInsmCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SsbsectInsmCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_CRN
        /// </summary>
        [Newtonsoft.Json.JsonProperty("crn", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Crn { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFTREGS_LEVL_CODE, Lookup lineage reference object : stvlevl,scrlevl,scrlevl
        /// </summary>
        [Newtonsoft.Json.JsonProperty("levlCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string LevlCode { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sfbetrm
    {
        [Newtonsoft.Json.JsonProperty("stvrgreDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StvrgreDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFBETRM_AR_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("arInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ArInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFBETRM_RGRE_CODE, Lookup lineage reference object : stvrgre
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rgreCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RgreCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stvestsDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StvestsDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("frDiscountDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FrDiscountDisplay { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("deleteAllCrnsInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DeleteAllCrnsInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFBETRM_MIN_HRS, Lookup lineage reference object : stvastd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("minHrs", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double MinHrs { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("maxhSrceCde", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? MaxhSrceCde { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("holdBlckCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? HoldBlckCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFBETRM_ESTS_CODE, Lookup lineage reference object : stvests
        /// </summary>
        [Newtonsoft.Json.JsonProperty("estsCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string EstsCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFBETRM_ESTS_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("estsDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? EstsDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("processBlockInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ProcessBlockInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFBETRM_MHRS_OVER, Lookup lineage reference object : stvastd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("mhrsOver", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double MhrsOver { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("minhSrceCde", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? MinhSrceCde { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sfrensp
    {
        /// <summary>
        /// Lineage reference object : SFRENSP_ESTS_CODE, Lookup lineage reference object : stvests
        /// </summary>
        [Newtonsoft.Json.JsonProperty("estsCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EstsCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("regAllowed", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RegAllowed { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("holdSpBlckCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? HoldSpBlckCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("processSpBlockInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ProcessSpBlockInd { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("spEstsDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SpEstsDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFRENSP_KEY_SEQNO, Lookup lineage reference object : sovlcur,stvastd,stvcast,sgvstsp,sgrstsp,stvastd,stvcast,sgvstsp,sgrstsp,sovlcur
        /// </summary>
        [Newtonsoft.Json.JsonProperty("keySeqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? KeySeqno { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sgbstdn
    {
        [Newtonsoft.Json.JsonProperty("termCastDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCastDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("astdDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AstdDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("advrName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AdvrName { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("termEffDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermEffDesc { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvcast
        /// </summary>
        [Newtonsoft.Json.JsonProperty("xxxxxxxCastCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? XxxxxxxCastCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("lastTermAttended", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LastTermAttended { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("ststDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StstDesc { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvprev
        /// </summary>
        [Newtonsoft.Json.JsonProperty("xxxxxxxPrevCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? XxxxxxxPrevCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_RATE_CODE, Lookup lineage reference object : stvrate
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rateCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RateCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("resdDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ResdDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("xxxxxxxTermCodePrev", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? XxxxxxxTermCodePrev { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stypDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StypDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stvscpcDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StvscpcDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("fullPartDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FullPartDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("xxxxxxxTermCodeCast", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? XxxxxxxTermCodeCast { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("termPrevDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermPrevDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_FULL_PART_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fullPartInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FullPartInd { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("castDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CastDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("termAstdDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermAstdDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_TERM_CODE_EFF
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeEff", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeEff { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvastd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("xxxxxxxAstdCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? XxxxxxxAstdCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("prevDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PrevDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_RESD_CODE, Lookup lineage reference object : stvresd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("resdCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string ResdCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("blckDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BlckDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("termaDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermaDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_SCPC_CODE, Lookup lineage reference object : stvscpc,sobscps,sorscpt
        /// </summary>
        [Newtonsoft.Json.JsonProperty("scpcCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ScpcCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("rateDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RateDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_STST_CODE, Lookup lineage reference object : stvstst
        /// </summary>
        [Newtonsoft.Json.JsonProperty("ststCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string StstCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_BLCK_CODE, Lookup lineage reference object : stvblck
        /// </summary>
        [Newtonsoft.Json.JsonProperty("blckCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BlckCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGBSTDN_STYP_CODE, Lookup lineage reference object : stvstyp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("stypCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string StypCode { get; set; } = default!;

        /// <summary>
        /// Lookup lineage reference object : stvclas
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sgrclsrClasCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SgrclsrClasCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("clasDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ClasDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("xxxxxxxTermCodeAstd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? XxxxxxxTermCodeAstd { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sorlcur
    {
        [Newtonsoft.Json.JsonProperty("programDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ProgramDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_LEAV_CODE, Lookup lineage reference object : stvleav
        /// </summary>
        [Newtonsoft.Json.JsonProperty("leavCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LeavCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_END_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("endDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? EndDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("admtTermDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AdmtTermDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_DEGC_CODE, Lookup lineage reference object : stvdegc
        /// </summary>
        [Newtonsoft.Json.JsonProperty("degcCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DegcCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("matricTermDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? MatricTermDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_PROGRAM, Lookup lineage reference object : smrprle
        /// </summary>
        [Newtonsoft.Json.JsonProperty("program", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Program { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("leavCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LeavCodeDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("catlgTermDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CatlgTermDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("lcurRolledKeySeqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? LcurRolledKeySeqno { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_CAMP_CODE, Lookup lineage reference object : stvcamp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("campCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CampCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("termDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_CACT_CODE, Lookup lineage reference object : stvcact,sobcact
        /// </summary>
        [Newtonsoft.Json.JsonProperty("cactCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CactCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_LEAV_FROM_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("leavFromDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? LeavFromDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("lmodCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LmodCodeDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("termCodeGradDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeGradDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("campDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CampDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_LMOD_CODE, Lookup lineage reference object : stvlmod
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lmodCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LmodCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_ROLL_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rollInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RollInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_APPL_KEY_SEQNO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sovlcurApplKeySeqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? SovlcurApplKeySeqno { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_COLL_CODE, Lookup lineage reference object : stvcoll
        /// </summary>
        [Newtonsoft.Json.JsonProperty("collCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CollCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_LEVL_CODE, Lookup lineage reference object : stvlevl
        /// </summary>
        [Newtonsoft.Json.JsonProperty("levlCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LevlCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_START_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("startDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? StartDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("rateCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RateCodeDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_TERM_CODE_MATRIC, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeMatric", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeMatric { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_RATE_CODE, Lookup lineage reference object : stvrate
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rateCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? RateCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_TERM_CODE_GRAD, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeGrad", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeGrad { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_GAPP_SEQNO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("gappSeqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? GappSeqno { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_ACTIVITY_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("activityDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? ActivityDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_ADMT_CODE, Lookup lineage reference object : stvadmt
        /// </summary>
        [Newtonsoft.Json.JsonProperty("admtCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AdmtCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_PRIORITY_NO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("priorityNo", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? PriorityNo { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_LEAV_TO_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("leavToDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? LeavToDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("collDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CollDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stypCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StypCodeDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_EXP_GRAD_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("expGradDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? ExpGradDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("levlDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LevlDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_TERM_CODE_CTLG, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeCtlg", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeCtlg { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_SITE_CODE, Lookup lineage reference object : stvsite
        /// </summary>
        [Newtonsoft.Json.JsonProperty("siteCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SiteCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_SEQNO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("seqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Seqno { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_CURRENT_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sovlcurCurrentInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SovlcurCurrentInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_TERM_CODE_END, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeEnd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeEnd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_USER_ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty("userId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? UserId { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("degcDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DegcDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_KEY_SEQNO, Lookup lineage reference object : sgvstsp,sgrstsp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("keySeqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? KeySeqno { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_ACYR_CODE, Lookup lineage reference object : stvacyr
        /// </summary>
        [Newtonsoft.Json.JsonProperty("acyrCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AcyrCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_TERM_CODE_ADMIT, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeAdmit", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeAdmit { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_STYP_CODE, Lookup lineage reference object : stvstyp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("stypCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StypCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("endTermDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EndTermDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("siteCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SiteCodeDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("acyrCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AcyrCodeDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("admtDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AdmtDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLCUR_TERM_CODE, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCode { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sorlfos
    {
        /// <summary>
        /// Lineage reference object : SOVLFOS_TERM_CODE_CTLG, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeCtlg", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeCtlg { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_MAJR_CODE_ATTACH, Lookup lineage reference object : sobcact,stvmajr,sotlfos,sotlfos
        /// </summary>
        [Newtonsoft.Json.JsonProperty("majrCodeAttach", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? MajrCodeAttach { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_SEQNO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("seqno", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? Seqno { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("tmstDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TmstDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_END_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("endDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? EndDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("majrDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? MajrDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_TMST_CODE, Lookup lineage reference object : stvtmst
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tmstCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TmstCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("lfosRolledInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LfosRolledInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_MAJR_CODE, Lookup lineage reference object : stvmajr,sovlfos
        /// </summary>
        [Newtonsoft.Json.JsonProperty("majrCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? MajrCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_TERM_CODE_END, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeEnd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeEnd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_USER_ID
        /// </summary>
        [Newtonsoft.Json.JsonProperty("userId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? UserId { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_CURRENT_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("currentInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CurrentInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_LFST_CODE, Lookup lineage reference object : gtvlfst
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lfstCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LfstCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_ACTIVITY_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("activityDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? ActivityDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_PRIORITY_NO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("priorityNo", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? PriorityNo { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("attachConcDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AttachConcDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("deptDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DeptDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_CSTS_CODE, Lookup lineage reference object : stvcsts
        /// </summary>
        [Newtonsoft.Json.JsonProperty("cstsCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CstsCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_DEPT_CODE, Lookup lineage reference object : stvdept
        /// </summary>
        [Newtonsoft.Json.JsonProperty("deptCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DeptCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("lfstCodeDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LfstCodeDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_START_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("startDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? StartDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_CACT_CODE, Lookup lineage reference object : stvcact,sobcact
        /// </summary>
        [Newtonsoft.Json.JsonProperty("cactCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CactCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SOVLFOS_TERM_CODE, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCode { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class S_curricula_traditional
    {
        /// <summary>
        /// Lineage reference object : lcurRecCnt
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurRecCnt", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object? LcurRecCnt { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurCollegeDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurCollegeDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurCollegeDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : dataSeparatorLine2a
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dataSeparatorLine2a", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DataSeparatorLine2a { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurLmodCodeDisplay, Lookup lineage reference object : stvlmod
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurLmodCodeDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurLmodCodeDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurRecNum
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurRecNum", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object? LcurRecNum { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurSeqnoDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurSeqnoDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? LcurSeqnoDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurCampusDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurCampusDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurCampusDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurPriorityDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurPriorityDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurPriorityDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurDegreeDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurDegreeDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurDegreeDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurKeySeqnoDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurKeySeqnoDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? LcurKeySeqnoDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : dataSeparatorLine1
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dataSeparatorLine1", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DataSeparatorLine1 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurCactCodeDisplay, Lookup lineage reference object : stvcact,sobcact
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurCactCodeDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurCactCodeDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurTermCodeDisplay, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurTermCodeDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurTermCodeDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : dataSeparatorLine2
        /// </summary>
        [Newtonsoft.Json.JsonProperty("dataSeparatorLine2", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? DataSeparatorLine2 { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurLevelDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurLevelDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurLevelDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurCurrentIndDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurCurrentIndDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurCurrentIndDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurRecCntLfos
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurRecCntLfos", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object? LcurRecCntLfos { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurRecNumLfos
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurRecNumLfos", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public object? LcurRecNumLfos { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurCatlgDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurCatlgDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurCatlgDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurTermCodeEndDisplay, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurTermCodeEndDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurTermCodeEndDisplay { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : lcurProgramDisplay
        /// </summary>
        [Newtonsoft.Json.JsonProperty("lcurProgramDisplay", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? LcurProgramDisplay { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sgrstsp
    {
        [Newtonsoft.Json.JsonProperty("gainDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? GainDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("astdDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AstdDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_PREV_CODE, Lookup lineage reference object : stvprev
        /// </summary>
        [Newtonsoft.Json.JsonProperty("prevCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PrevCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("egolDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EgolDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_INCM_CODE, Lookup lineage reference object : stvincm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("incmCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? IncmCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_EDLV_CODE, Lookup lineage reference object : stvedlv
        /// </summary>
        [Newtonsoft.Json.JsonProperty("edlvCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EdlvCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("caplDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CaplDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_STSP_CODE, Lookup lineage reference object : saturn,stvstsp
        /// </summary>
        [Newtonsoft.Json.JsonProperty("stspCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string StspCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sessDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SessDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("resdDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ResdDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("voedDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? VoedDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_SESS_CODE, Lookup lineage reference object : stvsess
        /// </summary>
        [Newtonsoft.Json.JsonProperty("sessCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SessCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_PRAC_CODE, Lookup lineage reference object : stvprac
        /// </summary>
        [Newtonsoft.Json.JsonProperty("pracCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PracCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("incmDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? IncmDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_EMEX_CODE, Lookup lineage reference object : stvemex
        /// </summary>
        [Newtonsoft.Json.JsonProperty("emexCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EmexCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_TRCN_CODE, Lookup lineage reference object : stvtrcn
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trcnCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrcnCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_CAST_CODE, Lookup lineage reference object : stvcast
        /// </summary>
        [Newtonsoft.Json.JsonProperty("castCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CastCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("aprnDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AprnDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_FULL_PART_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("fullPartInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? FullPartInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_ORSN_CODE, Lookup lineage reference object : stvorsn
        /// </summary>
        [Newtonsoft.Json.JsonProperty("orsnCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OrsnCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("castDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CastDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_TERM_CODE_EFF, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeEff", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string TermCodeEff { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_CAPL_CODE, Lookup lineage reference object : stvcapl
        /// </summary>
        [Newtonsoft.Json.JsonProperty("caplCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CaplCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("prevDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PrevDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_RESD_CODE, Lookup lineage reference object : stvresd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("resdCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ResdCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("edlvDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EdlvDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("blckDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BlckDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("bsklDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BsklDesc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("endStspTerm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EndStspTerm { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stspDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StspDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_KEY_SEQNO
        /// </summary>
        [Newtonsoft.Json.JsonProperty("keySeqno", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double KeySeqno { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("pracDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? PracDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_BSKL_CODE, Lookup lineage reference object : stvbskl
        /// </summary>
        [Newtonsoft.Json.JsonProperty("bsklCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BsklCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("trcnDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrcnDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_BLCK_CODE, Lookup lineage reference object : stvblck
        /// </summary>
        [Newtonsoft.Json.JsonProperty("blckCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? BlckCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_EGOL_CODE, Lookup lineage reference object : stvegol
        /// </summary>
        [Newtonsoft.Json.JsonProperty("egolCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EgolCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Name { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_APRN_CODE, Lookup lineage reference object : stvaprn
        /// </summary>
        [Newtonsoft.Json.JsonProperty("aprnCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AprnCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("orsnDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? OrsnDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_GAIN_CODE, Lookup lineage reference object : stvgain
        /// </summary>
        [Newtonsoft.Json.JsonProperty("gainCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? GainCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_VOED_CODE, Lookup lineage reference object : stvvoed
        /// </summary>
        [Newtonsoft.Json.JsonProperty("voedCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? VoedCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SGRSTSP_ASTD_CODE, Lookup lineage reference object : stvastd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("astdCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? AstdCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("emexDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? EmexDesc { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Sfrthst
    {
        [Newtonsoft.Json.JsonProperty("holdTmstDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? HoldTmstDate { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFRTHST_ACTIVITY_DATE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("activityDate", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? ActivityDate { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("tmstMaintIndDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TmstMaintIndDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SFRTHST_TMST_CODE, Lookup lineage reference object : stvtmst
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tmstCode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string TmstCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("term", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Term { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("holdTmstTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? HoldTmstTime { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("stvtmstDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? StvtmstDesc { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603