//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Ellucian.Generated.BpApi.Ban.TransferInstitutionCatalogEntry100GetResponse
{
    using System = global::System;

    

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TransferInstitutionCatalogEntry100GetResponse
    {
        [Newtonsoft.Json.JsonProperty("shrtcat", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Shrtcat>? Shrtcat { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("shbtatc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Shbtatc>? Shbtatc { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("shrtcmt", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<Shrtcmt>? Shrtcmt { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Shrtcat
    {
        /// <summary>
        /// Lineage reference object : SHRTCAT_ATTR_CDE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("attrCde", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AttrCde { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHRTCAT_ATTR_DESC
        /// </summary>
        [Newtonsoft.Json.JsonProperty("attrDesc", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string AttrDesc { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Shbtatc
    {
        /// <summary>
        /// Lineage reference object : SHBTATC_TERM_CODE_EFF_TRNS, Lookup lineage reference object : stvterm
        /// </summary>
        [Newtonsoft.Json.JsonProperty("termCodeEffTrns", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TermCodeEffTrns { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_PROTECT_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("protectInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? ProtectInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TRNS_HIGH_HRS
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trnsHighHrs", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? TrnsHighHrs { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_CRSE_NUMB_TRNS
        /// </summary>
        [Newtonsoft.Json.JsonProperty("crseNumbTrns", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CrseNumbTrns { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TRNS_CATALOG
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trnsCatalog", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrnsCatalog { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TRNS_LOW_HRS
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trnsLowHrs", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double? TrnsLowHrs { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TLVL_CODE, Lookup lineage reference object : stvtlvl,sorbtal,sorbtal
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tlvlCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TlvlCode { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TRNS_TITLE
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trnsTitle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrnsTitle { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_GROUP_PRIMARY_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("groupPrimaryInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? GroupPrimaryInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_CRSE_DESC
        /// </summary>
        [Newtonsoft.Json.JsonProperty("crseDesc", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? CrseDesc { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TRNS_REVIEW_IND
        /// </summary>
        [Newtonsoft.Json.JsonProperty("trnsReviewInd", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TrnsReviewInd { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TGRD_CODE_MIN, Lookup lineage reference object : shrtgrd,shrtgrd,shrtgrd
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tgrdCodeMin", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TgrdCodeMin { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_SUBJ_CODE_TRNS
        /// </summary>
        [Newtonsoft.Json.JsonProperty("subjCodeTrns", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? SubjCodeTrns { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_GROUP
        /// </summary>
        [Newtonsoft.Json.JsonProperty("group", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Group { get; set; } = default!;

        /// <summary>
        /// Lineage reference object : SHBTATC_TAST_CODE, Lookup lineage reference object : stvtast
        /// </summary>
        [Newtonsoft.Json.JsonProperty("tastCode", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? TastCode { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.16.1.0 (NJsonSchema v10.7.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Shrtcmt
    {
        /// <summary>
        /// Lineage reference object : SHRTCMT_TEXT
        /// </summary>
        [Newtonsoft.Json.JsonProperty("text", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string? Text { get; set; } = default!;

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties = new System.Collections.Generic.Dictionary<string, object>();

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties; }
            set { _additionalProperties = value; }
        }

    }


}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
#pragma warning restore 3016
#pragma warning restore 8603